### PR TITLE
Reassign iterator after erasing element in std::vector

### PR DESCRIPTION
**Pull request by mutalibmohammed**
Iterator is invalidated when erasing element in Vector, hence reassign iterator variable to the iterator returned by erase.

### CODE REVIEW

**Comment by mutalibmohammed** [comment]
#rerun tests

**Comment by mutalibmohammed** [comment]
#rerun tests

**Comment by FinnWilkinson** [comment]
Please rebase this onto dev

**Comment by FinnWilkinson** [comment]
Including this change in PR #274 in order to get it into `dev` branch seeing as it is so small, and we would like to get it into Dev ASAP. Thanks for finding it!

**Pull request closed without merging**
