### PR TITLE
Dispatch rate SE-146

### PR DESCRIPTION
**Pull request by jj16791**
This PR moves the dispatch rate restriction from dispatch unit wide to the individual reservation stations. This improves the parameterization of the unit as a whole.

### CODE REVIEW

**Review by FinnWilkinson — CHANGES_REQUESTED** [review]
Generally all ok, just a few points

**Review by FinnWilkinson — APPROVED** [review]
Everything looks good to me

**Review by dANW34V3R — APPROVED** [review]
All looks good

**Comment by jj16791** [comment]
#rerun tests

**Review by rahahahat — APPROVED** [review]

**Review by rahahahat — APPROVED** [review]

**Pull request merged**
