### PR TITLE
Further AArch64 Support & Syscall OS Nuance Fixes

### PR DESCRIPTION
**Pull request by FinnWilkinson**
This pull request mainly contains aditional AArch64 instructions (inc. sve) and syscalls needed by the TeaLeaf benchmark (this branch was rebased onto the TeaLeaf-benchmark branch). 

There are also some fixes to : 

- Syscall issues that arrose when running SimEng on MacOS as well as Isambard
- Minor fixex to deal wth sanitizer errors
- Fixed minor errors that arrose from invalid speculated instructions
- Ammended SCVTF and FCVT sve implementations and added more relevant test cased

### CODE REVIEW

**Comment by FinnWilkinson** [comment]
Faccessat syscall test failing poissibly due to different file structure on Jenkins. Filepath used in test needs re-evaluating and/or print statements need pushing to PR to evaluate where in file directory the tests are being executed from

- Want test to be relative to the current working directory as we need to test that the use of `AT_FDCWD` as the dirfd works correctly
- The current implementation works on my local machine, but was initially failing when executing the tests in different ways due to differing CWD; so the same thing is probably happening on the Jenkins pipeline

**Comment by FinnWilkinson** [comment]
No more commits are expected for this PR

**Comment by FinnWilkinson** [comment]
#rerun tests

**Comment by jj16791** [comment]
#rerun tests

**Pull request merged**
